### ISSUE TITLE
Failed to compile on Ubuntu 18.04

### ISSUE THREAD

**Issue by gfursin** [Chunosov/ck-gui#5]
After

$ ck run gui

Maybe you need Qt5 instead of Qt4?

```
g++-8 -c -m64 -pipe -std=c++11 -O2 -Wall -W -D_REENTRANT -DQT_USE_QSTRINGBUILDER -DQT_DEPRECATED_WARNINGS -DQT_NO_DEBUG -DQT_SVG_LIB -DQT_GUI_LIB -DQT_CORE_LIB -DQT_SHARED -I/usr/share/qt4/mkspecs/linux-g++-64 -I../../ck-gui-qt -I/usr/include/qt4/QtCore -I/usr/include/qt4/QtGui -I/usr/include/qt4/QtSvg -I/usr/include/qt4 -I../../../../local/env/9495e87bbbd3ce16/src -I. -I../../ck-gui-qt -I. -o OriMdiToolBar.o ../../../../local/env/9495e87bbbd3ce16/src/widgets/OriMdiToolBar.cpp
../../../../local/env/9495e87bbbd3ce16/src/widgets/OriMdiToolBar.cpp: In constructor âOri::Widgets::MdiToolBar::MdiToolBar(const QString&, QMdiArea*)â:
../../../../local/env/9495e87bbbd3ce16/src/widgets/OriMdiToolBar.cpp:24:33: error: âvoid QMdiArea::subWindowActivated(QMdiSubWindow*)â is protected within this context
     connect(mdiArea, &QMdiArea::subWindowActivated, this, &MdiToolBar::subWindowActivated);
                                 ^~~~~~~~~~~~~~~~~~
In file included from /usr/include/qt4/QtGui/QMdiArea:1,
                 from ../../../../local/env/9495e87bbbd3ce16/src/widgets/OriMdiToolBar.cpp:5:
/usr/include/qt4/QtGui/qmdiarea.h:137:10: note: declared protected here
     void subWindowActivated(QMdiSubWindow *);
          ^~~~~~~~~~~~~~~~~~
../../../../local/env/9495e87bbbd3ce16/src/widgets/OriMdiToolBar.cpp:24:90: error: no matching function for call to âOri::Widgets::MdiToolBar::connect(QMdiArea*&, void (QMdiArea::*)(QMdiSubWindow*), Ori::Widgets::MdiToolBar*, void (Ori::Widgets::MdiToolBar::*)(QMdiSubWindow*))â
     connect(mdiArea, &QMdiArea::subWindowActivated, this, &MdiToolBar::subWindowActivated);
                                                                                          ^
In file included from /usr/include/qt4/QtGui/qwidget.h:47,
                 from /usr/include/qt4/QtGui/qtoolbar.h:45,
                 from /usr/include/qt4/QtGui/QToolBar:1,
                 from ../../../../local/env/9495e87bbbd3ce16/src/widgets/OriMdiToolBar.h:4,
                 from ../../../../local/env/9495e87bbbd3ce16/src/widgets/OriMdiToolBar.cpp:1:
/usr/include/qt4/QtCore/qobject.h:204:17: note: candidate: âstatic bool QObject::connect(const QObject*, const char*, const QObject*, const char*, Qt::ConnectionType)â
     static bool connect(const QObject *sender, const char *signal,
                 ^~~~~~~
/usr/include/qt4/QtCore/qobject.h:204:17: note:   no known conversion for argument 2 from âvoid (QMdiArea::*)(QMdiSubWindow*)â to âconst char*â
/usr/include/qt4/QtCore/qobject.h:217:17: note: candidate: âstatic bool QObject::connect(const QObject*, const QMetaMethod&, const QObject*, const QMetaMethod&, Qt::ConnectionType)â
     static bool connect(const QObject *sender, const QMetaMethod &signal,
                 ^~~~~~~
/usr/include/qt4/QtCore/qobject.h:217:17: note:   no known conversion for argument 2 from âvoid (QMdiArea::*)(QMdiSubWindow*)â to âconst QMetaMethod&â
/usr/include/qt4/QtCore/qobject.h:337:13: note: candidate: âbool QObject::connect(const QObject*, const char*, const char*, Qt::ConnectionType) constâ
 inline bool QObject::connect(const QObject *asender, const char *asignal,
             ^~~~~~~
/usr/include/qt4/QtCore/qobject.h:337:13: note:   no known conversion for argument 2 from âvoid (QMdiArea::*)(QMdiSubWindow*)â to âconst char*â
../../../../local/env/9495e87bbbd3ce16/src/widgets/OriMdiToolBar.cpp: In member function âvoid Ori::Widgets::MdiToolBar::subWindowActivated(QMdiSubWindow*)â:
../../../../local/env/9495e87bbbd3ce16/src/widgets/OriMdiToolBar.cpp:52:37: error: âvoid QObject::destroyed(QObject*)â is protected within this context
     connect(window, &QMdiSubWindow::destroyed, this, &MdiToolBar::subWindowDestroyed);
                                     ^~~~~~~~~
In file included from /usr/include/qt4/QtGui/qwidget.h:47,
                 from /usr/include/qt4/QtGui/qtoolbar.h:45,
                 from /usr/include/qt4/QtGui/QToolBar:1,
                 from ../../../../local/env/9495e87bbbd3ce16/src/widgets/OriMdiToolBar.h:4,
                 from ../../../../local/env/9495e87bbbd3ce16/src/widgets/OriMdiToolBar.cpp:1:
/usr/include/qt4/QtCore/qobject.h:270:10: note: declared protected here
     void destroyed(QObject * = 0);
          ^~~~~~~~~
../../../../local/env/9495e87bbbd3ce16/src/widgets/OriMdiToolBar.cpp:52:85: error: no matching function for call to âOri::Widgets::MdiToolBar::connect(QMdiSubWindow*&, void (QObject::*)(QObject*), Ori::Widgets::MdiToolBar*, void (Ori::Widgets::MdiToolBar::*)(QObject*))â
     connect(window, &QMdiSubWindow::destroyed, this, &MdiToolBar::subWindowDestroyed);
                                                                                     ^
In file included from /usr/include/qt4/QtGui/qwidget.h:47,
                 from /usr/include/qt4/QtGui/qtoolbar.h:45,
                 from /usr/include/qt4/QtGui/QToolBar:1,
                 from ../../../../local/env/9495e87bbbd3ce16/src/widgets/OriMdiToolBar.h:4,
                 from ../../../../local/env/9495e87bbbd3ce16/src/widgets/OriMdiToolBar.cpp:1:
/usr/include/qt4/QtCore/qobject.h:204:17: note: candidate: âstatic bool QObject::connect(const QObject*, const char*, const QObject*, const char*, Qt::ConnectionType)â
     static bool connect(const QObject *sender, const char *signal,
                 ^~~~~~~
/usr/include/qt4/QtCore/qobject.h:204:17: note:   no known conversion for argument 2 from âvoid (QObject::*)(QObject*)â to âconst char*â
/usr/include/qt4/QtCore/qobject.h:217:17: note: candidate: âstatic bool QObject::connect(const QObject*, const QMetaMethod&, const QObject*, const QMetaMethod&, Qt::ConnectionType)â
     static bool connect(const QObject *sender, const QMetaMethod &signal,
                 ^~~~~~~
/usr/include/qt4/QtCore/qobject.h:217:17: note:   no known conversion for argument 2 from âvoid (QObject::*)(QObject*)â to âconst QMetaMethod&â
/usr/include/qt4/QtCore/qobject.h:337:13: note: candidate: âbool QObject::connect(const QObject*, const char*, const char*, Qt::ConnectionType) constâ
 inline bool QObject::connect(const QObject *asender, const char *asignal,
             ^~~~~~~
/usr/include/qt4/QtCore/qobject.h:337:13: note:   no known conversion for argument 2 from âvoid (QObject::*)(QObject*)â to âconst char*â
../../../../local/env/9495e87bbbd3ce16/src/widgets/OriMdiToolBar.cpp:53:37: error: âwindowTitleChangedâ is not a member of âQMdiSubWindowâ
     connect(window, &QMdiSubWindow::windowTitleChanged, this, &MdiToolBar::subWindowTitleChanged);
                                     ^~~~~~~~~~~~~~~~~~
../../../../local/env/9495e87bbbd3ce16/src/widgets/OriMdiToolBar.cpp:54:37: error: âwindowIconChangedâ is not a member of âQMdiSubWindowâ
     connect(window, &QMdiSubWindow::windowIconChanged, this, &MdiToolBar::subWindowIconChanged);
                                     ^~~~~~~~~~~~~~~~~
In file included from /usr/include/qt4/QtCore/qvariant.h:48,
                 from /usr/include/qt4/QtGui/qaction.h:48,
                 from /usr/include/qt4/QtGui/QAction:1,
                 from ../../../../local/env/9495e87bbbd3ce16/src/widgets/OriMdiToolBar.cpp:3:
/usr/include/qt4/QtCore/qmetatype.h: In instantiation of âstatic int QMetaTypeId2<T>::qt_metatype_id() [with T = QMdiSubWindow*]â:
/usr/include/qt4/QtCore/qmetatype.h:230:43:   required from âint qMetaTypeId(T*) [with T = QMdiSubWindow*]â
/usr/include/qt4/QtCore/qvariant.h:573:35:   required from âT qvariant_cast(const QVariant&) [with T = QMdiSubWindow*]â
../../../../local/env/9495e87bbbd3ce16/src/widgets/OriMdiToolBar.cpp:92:73:   required from here
/usr/include/qt4/QtCore/qmetatype.h:169:79: error: âqt_metatype_idâ is not a member of âQMetaTypeId<QMdiSubWindow*>â
     static inline int qt_metatype_id() { return QMetaTypeId<T>::qt_metatype_id(); }
                                                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^~
Makefile:443: recipe for target 'OriMdiToolBar.o' failed
make: *** [OriMdiToolBar.o] Error 1
cp: cannot stat '../bin/ck-gui': No such file or directory
executing code ...
./tmp-BPU87r.sh: line 17: ./ck-gui: No such file or directory
```

**Comment by Chunosov** [comment]
Yes, it is because of Qt 4. The app needs version 5. I will check how we can limit dependent Qt version.
